{
 "title": "Heizung",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Umgebungstemperaturen",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Außen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Umgebungstemperaturen",
     "select": [
      [
       { "params": [ "Außentemperatur" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Raum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Umgebungstemperaturen",
     "select": [
      [
       { "params": [ "Raumtemperatur" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Umschaltventil",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Umschaltventil",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizungsstatus",
     "select": [
      [
       { "params": [ "Umschaltventil" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Brennerstarts pro Tag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Brennerstarts",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Lebenszyklus",
     "query": "SELECT cumulative_sum(derivative(distinct(\"Brennerstarts\"), 1d)) FROM \"Lebenszyklus\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Brennerstarts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heizungstemperaturen",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Abgas",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizungstemperaturen",
     "select": [
      [
       { "params": [ "Abgastemperatur" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Kessel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizungstemperaturen",
     "select": [
      [
       { "params": [ "Kesseltemperatur" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Vorlauf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizungstemperaturen",
     "select": [
      [
       { "params": [ "Vorlauftemperatur" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Warmwasser",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizungstemperaturen",
     "select": [
      [
       { "params": [ "Warmwassertemperatur" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Vorlauf-Soll",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizungstemperaturen",
     "select": [
      [
       { "params": [ "Vorlaufsolltemperatur" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Akt. Brennerleistung",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Leistung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizungsstatus",
     "select": [
      [
       { "params": [ "Brennerleistung" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Brennerstatus",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizungsstatus",
     "select": [
      [
       { "params": [ "Brennerstatus" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Flammenstatus",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizungsstatus",
     "select": [
      [
       { "params": [ "Flammenstatus" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Brennerstunden",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Brennerstunden",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Lebenszyklus",
     "select": [
      [
       { "params": [ "Brennerstunden" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Brennerstarts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Lebenszyklus",
     "select": [
      [
       { "params": [ "Brennerstarts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pumpen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Heizkreispumpe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizungsstatus",
     "select": [
      [
       { "params": [ "Heizkreispumpe" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Interne  Pumpe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Heizungsstatus",
     "select": [
      [
       { "params": [ "Interne Pumpe" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  }
 ]
}